const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),url=require('url');
const ROOT=__dirname, DATA=path.join(ROOT,'data.json'), PORT=process.env.PORT||3000;
const ADMIN_USER=process.env.ADMIN_USER||'admin', ADMIN_PASS=process.env.ADMIN_PASS||'change-me-now';
const DEFAULT_ADMIN_PASSWORD_GUARD=ADMIN_PASS==='change-me-now';
const STATUSES=['New','Processing','Shipped','Delivered','Cancelled'];
function load(){try{return JSON.parse(fs.readFileSync(DATA,'utf8'))}catch{return {orders:[],newsletter:[],users:[],products:[],sessions:{}}}}
function save(db){fs.writeFileSync(DATA,JSON.stringify(db,null,2))}
function audit(action,details,actor='admin'){db.audit.unshift({id:crypto.randomUUID(),action,details:String(details||'').slice(0,500),actor,at:new Date().toISOString()});db.audit=db.audit.slice(0,500)}
function notify(type,title,message,meta={}){db.notifications.unshift({id:crypto.randomUUID(),type,title,message,meta,read:false,createdAt:new Date().toISOString()});db.notifications=db.notifications.slice(0,300)}
function couponFor(code){return db.coupons.find(c=>c.code===String(code||'').trim().toUpperCase()&&c.active!==false)}
const db=load(); db.orders ||= []; db.newsletter ||= []; db.users ||= []; db.products ||= []; db.sessions ||= {}; db.notifications ||= []; db.coupons ||= []; db.returns ||= []; db.audit ||= [];
db.products.forEach((p,i)=>{p.likeKeys ||= {};if(!p.id)p.id='p_'+crypto.createHash('sha1').update(p.name+'|'+p.image+'|'+i).digest('hex').slice(0,12);if(!p.sizes){const n=Math.max(0,Number(p.stock||0));p.sizes={S:n,M:n,L:n,XL:n,XXL:n}};p.category=p.category||'T-Shirts';p.active=p.active!==false;p.images=Array.isArray(p.images)&&p.images.length?p.images:[p.image]});db.reviews ||= [];db.users.forEach(u=>{u.wishlist ||= [];});
function hash(s){return crypto.createHash('sha256').update(String(s)).digest('hex')}
function send(res,status,data,type='application/json'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'SAMEORIGIN','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Content-Security-Policy':"default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob:; img-src 'self' data: blob:; media-src 'self' blob:",'Access-Control-Allow-Origin':reqOrigin,'Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,PATCH,DELETE,OPTIONS'});res.end(type==='application/json'?JSON.stringify(data):data)}
let reqOrigin='';const rate=new Map();function limited(req,key,limit=60,windowMs=60000){const now=Date.now(),ip=req.socket.remoteAddress||'local',k=key+ip,arr=(rate.get(k)||[]).filter(t=>now-t<windowMs);arr.push(now);rate.set(k,arr);return arr.length>limit}
function body(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>2e6){req.destroy();return reject(new Error('Payload too large'))}});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}});req.on('error',reject)})}
function tokenFor(req){const h=req.headers.authorization||'';return h.startsWith('Bearer ')?h.slice(7):''}
function auth(req,role){const t=tokenFor(req),s=db.sessions[t];return s&&s.expires>Date.now()&&(!role||s.role===role)?s:null}
function newSession(role,userId){const token=crypto.randomBytes(32).toString('hex');db.sessions[token]={role,userId:userId||null,expires:Date.now()+8*60*60*1000};save(db);return token}
function orderId(){return 'YT-'+Date.now().toString(36).toUpperCase()+'-'+crypto.randomBytes(2).toString('hex').toUpperCase()}
function safeProduct(p){const z=p.sizes||{S:0,M:0,L:0,XL:0,XXL:0};const sizes={S:Math.max(0,Number(z.S||0)),M:Math.max(0,Number(z.M||0)),L:Math.max(0,Number(z.L||0)),XL:Math.max(0,Number(z.XL||0)),XXL:Math.max(0,Number(z.XXL||0))};return {id:p.id,name:String(p.name||''),price:String(p.price||''),image:String(p.image||''),images:Array.isArray(p.images)&&p.images.length?p.images:[String(p.image||'')],badge:String(p.badge||''),oldPrice:String(p.oldPrice||''),category:String(p.category||'T-Shirts'),active:p.active!==false,sizes,colors:Array.isArray(p.colors)&&p.colors.length?p.colors:['Black'],featured:Boolean(p.featured),stock:Object.values(sizes).reduce((a,b)=>a+b,0),likes:Object.keys(p.likeKeys||{}).length}}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp','.mp4':'video/mp4','.txt':'text/plain; charset=utf-8'};
async function api(req,res,p){
 try{reqOrigin=req.headers.origin&&req.headers.origin===('http://'+req.headers.host)?req.headers.origin:'';if(limited(req,p.startsWith('/api/admin')?'admin':p.startsWith('/api/auth')?'auth':'api'))return send(res,429,{error:'Too many requests. Please try again shortly.'});
  if(req.method==='OPTIONS')return send(res,204,'','text/plain');
  if(req.method==='POST'&&p==='/api/admin/logout'){const t=tokenFor(req);if(t)delete db.sessions[t];save(db);return send(res,200,{ok:true})}
  if(req.method==='POST'&&p==='/api/admin/login'){const x=await body(req);if(process.env.NODE_ENV==='production'&&DEFAULT_ADMIN_PASSWORD_GUARD)return send(res,503,{error:'Admin credentials are not configured for production. Set ADMIN_USER and ADMIN_PASS.'});if(x.username!==ADMIN_USER||x.password!==ADMIN_PASS)return send(res,401,{error:'Invalid admin credentials'});return send(res,200,{token:newSession('admin')})}
  if(req.method==='POST'&&p==='/api/auth/signup'){const x=await body(req),name=String(x.name||'').trim(),email=String(x.email||'').trim().toLowerCase(),password=String(x.password||'');if(!name||!/^\S+@\S+\.\S+$/.test(email)||password.length<8)return send(res,400,{error:'Name, valid email and an 8+ character password are required'});if(db.users.some(u=>u.email===email))return send(res,409,{error:'Account already exists'});const u={id:crypto.randomUUID(),name,email,password:hash(password),createdAt:new Date().toISOString(),wishlist:[]};db.users.push(u);save(db);return send(res,201,{ok:true,token:newSession('customer',u.id),name,email})}
  if(req.method==='POST'&&p==='/api/auth/signin'){const x=await body(req),u=db.users.find(v=>v.email===String(x.email||'').trim().toLowerCase()&&v.password===hash(x.password||''));if(!u)return send(res,401,{error:'Invalid email or password'});u.wishlist ||= [];return send(res,200,{ok:true,token:newSession('customer',u.id),name:u.name,email:u.email,wishlist:u.wishlist})}
  if(req.method==='GET'&&p==='/api/auth/me'){const s=auth(req,'customer');if(!s)return send(res,401,{error:'Unauthorized'});const u=db.users.find(v=>v.id===s.userId);if(!u)return send(res,404,{error:'Account not found'});return send(res,200,{id:u.id,name:u.name,email:u.email,wishlist:u.wishlist||[]})}
  if(req.method==='PATCH'&&p==='/api/auth/profile'){const s=auth(req,'customer');if(!s)return send(res,401,{error:'Unauthorized'});const u=db.users.find(v=>v.id===s.userId);if(!u)return send(res,404,{error:'Account not found'});const x=await body(req),name=String(x.name||'').trim(),email=String(x.email||'').trim().toLowerCase();if(!name||!/^\S+@\S+\.\S+$/.test(email))return send(res,400,{error:'Enter a valid name and email'});if(db.users.some(v=>v.id!==u.id&&v.email===email))return send(res,409,{error:'Email already in use'});u.name=name;u.email=email;save(db);return send(res,200,{name,email})}
  if(req.method==='PUT'&&p==='/api/auth/wishlist'){const s=auth(req,'customer');if(!s)return send(res,401,{error:'Unauthorized'});const u=db.users.find(v=>v.id===s.userId);if(!u)return send(res,404,{error:'Account not found'});const x=await body(req);u.wishlist=Array.isArray(x.wishlist)?x.wishlist.map(String).slice(0,100):[];save(db);return send(res,200,{wishlist:u.wishlist})}
  if(req.method==='POST'&&p==='/api/auth/reset-request'){const x=await body(req),email=String(x.email||'').trim().toLowerCase(),u=db.users.find(v=>v.email===email);if(!u)return send(res,200,{ok:true,message:'If the account exists, a reset link has been generated.',sampleToken:null});const token=crypto.randomBytes(18).toString('hex');u.resetToken=token;u.resetExpires=Date.now()+15*60*1000;save(db);return send(res,200,{ok:true,message:'Reset token generated for this request.',sampleToken:token})}
  if(req.method==='POST'&&p==='/api/auth/reset'){const x=await body(req),email=String(x.email||'').trim().toLowerCase(),token=String(x.token||''),password=String(x.password||''),u=db.users.find(v=>v.email===email&&v.resetToken===token&&Number(v.resetExpires||0)>Date.now());if(!u||password.length<8)return send(res,400,{error:'Invalid/expired reset token or password too short'});u.password=hash(password);delete u.resetToken;delete u.resetExpires;save(db);return send(res,200,{ok:true})}
  if(req.method==='GET'&&p==='/api/auth/orders'){const s=auth(req,'customer');if(!s)return send(res,401,{error:'Unauthorized'});return send(res,200,{orders:db.orders.filter(o=>o.userId===s.userId).map(o=>({orderId:o.orderId,status:o.status,date:o.date,total:o.total,items:o.items,cancelable:['New','Processing'].includes(o.status)}))})}
  if(req.method==='POST'&&p.startsWith('/api/auth/orders/')&&p.endsWith('/cancel')){const s=auth(req,'customer');if(!s)return send(res,401,{error:'Unauthorized'});const id=decodeURIComponent(p.slice('/api/auth/orders/'.length,-7)),o=db.orders.find(v=>v.orderId===id&&v.userId===s.userId);if(!o)return send(res,404,{error:'Order not found'});if(!['New','Processing'].includes(o.status))return send(res,409,{error:'This order can no longer be cancelled'});for(const item of o.items||[]){const pr=db.products.find(v=>v.name===item.name&&v.image===item.image);if(pr)pr.sizes[item.size]=Number(pr.sizes[item.size]||0)+Number(item.qty||1)}o.status='Cancelled';o.cancelledAt=new Date().toISOString();audit('Customer cancelled order',o.orderId,'customer');notify('order','Customer cancelled order',o.orderId,{orderId:o.orderId});save(db);return send(res,200,{ok:true,status:o.status})}
  if(req.method==='POST'&&p==='/api/newsletter'){const x=await body(req),email=String(x.email||'').trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))return send(res,400,{error:'Invalid email'});if(!db.newsletter.some(v=>v.email===email))db.newsletter.push({email,createdAt:new Date().toISOString()});save(db);return send(res,201,{ok:true})}
  if(req.method==='GET'&&p==='/api/products')return send(res,200,{products:db.products.filter(v=>v.active!==false).map(safeProduct)});
  if(req.method==='POST'&&p==='/api/products/like'){const x=await body(req),name=String(x.product||'').trim(),visitor=String(x.visitorId||'').trim();if(!name)return send(res,400,{error:'Product is required'});const pr=db.products.find(v=>v.name===name);if(!pr)return send(res,404,{error:'Product not found'});pr.likeKeys ||= {};const sess=auth(req,'customer');const rawKey=sess?'user:'+sess.userId:(visitor?'visitor:'+visitor:'');if(!rawKey)return send(res,400,{error:'Like identity is required'});const key='k_'+hash(rawKey).slice(0,40);let liked=false;if(pr.likeKeys[key]){delete pr.likeKeys[key];}else{pr.likeKeys[key]=true;liked=true}audit(liked?'Product liked':'Product unliked',pr.name,sess?'customer':'visitor');save(db);return send(res,200,{ok:true,liked,likes:Object.keys(pr.likeKeys).length})}

  if(req.method==='GET'&&p.startsWith('/api/reviews/')){const name=decodeURIComponent(p.slice('/api/reviews/'.length));return send(res,200,{reviews:db.reviews.filter(r=>r.product===name&&r.approved!==false).slice(-50).reverse()})}
  if(req.method==='POST'&&p==='/api/reviews'){const x=await body(req),name=String(x.product||'').trim(),title=String(x.title||'').trim(),text=String(x.text||'').trim(),rating=Math.max(1,Math.min(5,Number(x.rating||5)));if(!name||!title||!text||text.length>800)return send(res,400,{error:'Product, title and review text are required'});const sess=auth(req,'customer');if(!sess)return send(res,401,{error:'Please sign in to review'});const purchased=db.orders.some(o=>o.userId===sess.userId&&o.status!=='Cancelled'&&o.items?.some(it=>it.name===name));if(!purchased)return send(res,403,{error:'You can review a product after purchasing it.'});if(db.reviews.some(r=>r.userId===sess.userId&&r.product===name))return send(res,409,{error:'You have already reviewed this product.'});const u=db.users.find(v=>v.id===sess.userId);db.reviews.push({id:crypto.randomUUID(),product:name,rating,title,text,name:u?.name||'Customer',userId:sess.userId,verified:true,approved:true,createdAt:new Date().toISOString()});save(db);return send(res,201,{ok:true})}
  if(req.method==='POST'&&p==='/api/coupons/validate'){const x=await body(req),c=couponFor(x.code);const subtotal=Math.max(0,Number(x.subtotal||0));if(!c)return send(res,404,{error:'Invalid or inactive coupon'});if(c.expiresAt&&new Date(c.expiresAt).getTime()<Date.now())return send(res,400,{error:'Coupon has expired'});if(c.usageLimit&&Number(c.uses||0)>=Number(c.usageLimit))return send(res,400,{error:'Coupon usage limit reached'});if(c.minOrder&&subtotal<Number(c.minOrder))return send(res,400,{error:'Minimum order value is ₹'+Number(c.minOrder).toLocaleString('en-IN')});let discount=c.type==='percent'?subtotal*(Number(c.value||0)/100):Number(c.value||0);discount=Math.min(subtotal,Math.max(0,discount));return send(res,200,{code:c.code,discount,finalSubtotal:subtotal-discount})}
  if(req.method==='POST'&&p==='/api/orders'){
    const x=await body(req);if(!x.name||!x.email||!x.phone||!x.address||!x.city||!/^\d{6}$/.test(String(x.pin))||!Array.isArray(x.items)||!x.items.length)return send(res,400,{error:'Complete shipping details and cart are required'});
    const requested=[];for(const item of x.items){const pr=db.products.find(v=>v.name===item.name&&v.image===item.image);if(!pr)return send(res,400,{error:'Product no longer available: '+item.name});const size=['S','M','L','XL','XXL'].includes(item.size)?item.size:'M';const qty=Math.max(1,Math.min(10,Number(item.qty||1)));if(Number(pr.sizes?.[size]||0)<qty)return send(res,409,{error:`${pr.name} size ${size} has only ${Number(pr.sizes?.[size]||0)} left`});requested.push({name:pr.name,image:pr.image,price:pr.price,size,qty})}
    requested.forEach(item=>{const pr=db.products.find(v=>v.name===item.name&&v.image===item.image);pr.sizes[item.size]=Math.max(0,Number(pr.sizes[item.size]||0)-Number(item.qty||1))});
    const customer=auth(req,'customer'),id=orderId(),subtotal=requested.reduce((sum,item)=>sum+((Number(String(item.price).replace(/[^0-9.]/g,''))||0)*Number(item.qty||1)),0),shipping=subtotal>=999?0:99,coupon=couponFor(x.coupon),discount=coupon&&(!coupon.expiresAt||new Date(coupon.expiresAt).getTime()>=Date.now())&&(!coupon.minOrder||subtotal>=Number(coupon.minOrder))&&(!coupon.usageLimit||Number(coupon.uses||0)<Number(coupon.usageLimit))?(coupon.type==='percent'?Math.min(subtotal,subtotal*Number(coupon.value||0)/100):Math.min(subtotal,Number(coupon.value||0))):0,total=Math.max(0,subtotal-discount+shipping),payment=['cod','online'].includes(x.payment)?x.payment:'cod',order={name:String(x.name).trim(),email:String(x.email).trim().toLowerCase(),phone:String(x.phone).trim(),address:String(x.address).trim(),city:String(x.city).trim(),pin:String(x.pin),items:requested,subtotal,shipping,discount,coupon:coupon?.code||'',total,payment,paymentStatus:payment==='online'?'Pending':'Pending',orderId:id,status:'New',date:new Date().toISOString(),userId:customer?.userId||null};
    db.orders.unshift(order);if(coupon)coupon.uses=Number(coupon.uses||0)+1;notify('order','New order received',id,{orderId:id,total:order.total,payment:order.payment});save(db);return send(res,201,{orderId:id,total:order.total,paymentStatus:order.paymentStatus})
  }
  if(req.method==='GET'&&p.startsWith('/api/orders/')){const id=decodeURIComponent(p.slice('/api/orders/'.length)),o=db.orders.find(v=>v.orderId===id);if(!o)return send(res,404,{error:'Order not found'});return send(res,200,{orderId:o.orderId,status:o.status,date:o.date,total:o.total,items:o.items})}
  if(req.method==='GET'&&p==='/api/admin/notifications'){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});return send(res,200,{notifications:db.notifications.slice(0,100),unread:db.notifications.filter(n=>!n.read).length})}
  if(req.method==='PATCH'&&p==='/api/admin/notifications/read'){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const x=await body(req);if(x.all)db.notifications.forEach(n=>n.read=true);else if(Array.isArray(x.ids))db.notifications.forEach(n=>{if(x.ids.includes(n.id))n.read=true});save(db);return send(res,200,{ok:true})}
  if(req.method==='DELETE'&&p==='/api/admin/notifications'){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});db.notifications=[];save(db);return send(res,200,{ok:true})}
  if(req.method==='GET'&&p==='/api/admin/data'){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});return send(res,200,{orders:db.orders,newsletter:db.newsletter,products:db.products.map(safeProduct),users:db.users.map(u=>({id:u.id,name:u.name,email:u.email,createdAt:u.createdAt})),reviews:db.reviews,coupons:db.coupons,returns:db.returns,audit:db.audit.slice(0,100),notifications:db.notifications.slice(0,100)})}
  if(req.method==='GET'&&p==='/api/admin/analytics'){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const now=Date.now(),day=86400000,active=db.orders.filter(o=>o.status!=='Cancelled'),rev=xs=>xs.reduce((s,o)=>s+Number(o.total||0),0),ordersSince=(d)=>db.orders.filter(o=>Number(new Date(o.date).getTime())>=now-d&&o.status!=='Cancelled'),sales={};active.forEach(o=>(o.items||[]).forEach(i=>sales[i.name]=(sales[i.name]||0)+Number(i.qty||1)));const today=ordersSince(day),week=ordersSince(7*day),month=ordersSince(30*day);return send(res,200,{todayOrders:today.length,todayRevenue:rev(today),weekOrders:week.length,weekRevenue:rev(week),monthOrders:month.length,monthRevenue:rev(month),cancelledOrders:db.orders.filter(o=>o.status==='Cancelled').length,cancelledValue:rev(db.orders.filter(o=>o.status==='Cancelled')),byStatus:STATUSES.map(s=>({status:s,count:db.orders.filter(o=>o.status===s).length})),topProducts:Object.entries(sales).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([name,qty])=>({name,qty}))})}
  if(req.method==='PATCH'&&p.startsWith('/api/admin/orders/')){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const id=decodeURIComponent(p.slice('/api/admin/orders/'.length)),x=await body(req),o=db.orders.find(v=>v.orderId===id);if(!o)return send(res,404,{error:'Order not found'});if(x.status&&!STATUSES.includes(x.status))return send(res,400,{error:'Invalid order status'});if(x.status){const prev=o.status;if(prev!==x.status&&x.status==='Cancelled'&&!o.cancelledAt){for(const item of o.items||[]){const pr=db.products.find(v=>v.name===item.name&&v.image===item.image);if(pr){pr.sizes=pr.sizes||{S:0,M:0,L:0,XL:0,XXL:0};pr.sizes[item.size]=Number(pr.sizes[item.size]||0)+Number(item.qty||1)}}o.cancelledAt=new Date().toISOString();notify('order','Order cancelled',o.orderId,{orderId:o.orderId,status:o.status});} if(prev==='Cancelled'&&x.status!=='Cancelled'){let canRestore=true;for(const item of o.items||[]){const pr=db.products.find(v=>v.name===item.name&&v.image===item.image);if(pr&&Number(pr.sizes?.[item.size]||0)<Number(item.qty||1))canRestore=false}if(!canRestore)return send(res,409,{error:'Insufficient stock to reactivate this order'});for(const item of o.items||[]){const pr=db.products.find(v=>v.name===item.name&&v.image===item.image);if(pr)pr.sizes[item.size]=Number(pr.sizes[item.size]||0)-Number(item.qty||1)}}o.status=x.status;if(o.status==='Cancelled'&&!o.cancelledAt)o.cancelledAt=new Date().toISOString();audit('Order status',o.orderId+' → '+o.status);notify('order','Order status updated',o.orderId,{orderId:o.orderId,status:o.status});}if(x.courier!==undefined)o.courier=String(x.courier).slice(0,120);if(x.trackingNumber!==undefined)o.trackingNumber=String(x.trackingNumber).slice(0,120);if(x.paymentStatus!==undefined&&['Pending','Paid','Failed','Refunded'].includes(String(x.paymentStatus)))o.paymentStatus=String(x.paymentStatus);if(x.notes!==undefined)o.notes=String(x.notes).slice(0,1000);if(o.status==='Shipped'&&!o.shippedAt)o.shippedAt=new Date().toISOString();if(o.status==='Delivered'&&!o.deliveredAt)o.deliveredAt=new Date().toISOString();save(db);return send(res,200,o)}
  if(req.method==='DELETE'&&p.startsWith('/api/admin/orders/')){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const id=decodeURIComponent(p.slice('/api/admin/orders/'.length)),before=db.orders.length;db.orders=db.orders.filter(v=>v.orderId!==id);if(before===db.orders.length)return send(res,404,{error:'Order not found'});save(db);return send(res,200,{ok:true})}
  if(req.method==='POST'&&p==='/api/admin/products'){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const x=await body(req);if(!x.name||!x.price||!x.image)return send(res,400,{error:'Name, price and image filename are required'});const pr=safeProduct({...x,id:'p_'+crypto.randomBytes(6).toString('hex'),sizes:x.sizes||{S:0,M:0,L:0,XL:0,XXL:0},images:x.images||[x.image],category:x.category||'T-Shirts'});pr.likeKeys={};db.products.push(pr);audit('Product created',pr.name);if(pr.stock<=5)notify('inventory','Low stock',pr.name,{productId:pr.id,stock:pr.stock});save(db);return send(res,201,pr)}
  if(req.method==='PATCH'&&p.startsWith('/api/admin/products/')){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const id=decodeURIComponent(p.slice('/api/admin/products/'.length)),x=await body(req),i=db.products.findIndex(v=>v.id===id);if(i<0)return send(res,404,{error:'Product not found'});const current=db.products[i];const updated=safeProduct({...current,...x,id:current.id,sizes:x.sizes||current.sizes,images:x.images||current.images,category:x.category||current.category});updated.likeKeys=current.likeKeys||{};if(!updated.name||!updated.price||!updated.image)return send(res,400,{error:'Name, price and image filename are required'});db.products[i]=updated;audit('Product updated',updated.name);if(updated.stock<=5)notify('inventory','Low stock',updated.name,{productId:updated.id,stock:updated.stock});save(db);return send(res,200,updated)}
  if(req.method==='DELETE'&&p.startsWith('/api/admin/products/')){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const id=decodeURIComponent(p.slice('/api/admin/products/'.length)),i=db.products.findIndex(v=>v.id===id);if(i<0)return send(res,404,{error:'Product not found'});const removed=db.products[i];db.products.splice(i,1);audit('Product deleted',removed.name);save(db);return send(res,200,{ok:true})}
  if(req.method==='POST'&&p==='/api/admin/products/bulk'){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const x=await body(req),ids=Array.isArray(x.ids)?x.ids.map(String):[];if(!ids.length)return send(res,400,{error:'Select at least one product'});const allowed=['hide','show','delete','category','stock'];if(!allowed.includes(x.action))return send(res,400,{error:'Invalid bulk action'});let changed=0,deleted=0;for(const pr of db.products){if(!ids.includes(String(pr.id)))continue;if(x.action==='hide'){pr.active=false;changed++}else if(x.action==='show'){pr.active=true;changed++}else if(x.action==='category'){const c=String(x.category||'').trim();if(!c)return send(res,400,{error:'Category is required'});pr.category=c;changed++}else if(x.action==='stock'){const incoming=x.sizes||{};pr.sizes=pr.sizes||{S:0,M:0,L:0,XL:0,XXL:0};for(const k of ['S','M','L','XL','XXL'])if(incoming[k]!==undefined)pr.sizes[k]=Math.max(0,Number(incoming[k])||0);changed++}}if(x.action==='delete'){const before=db.products.length;db.products=db.products.filter(pr=>!ids.includes(String(pr.id)));deleted=before-db.products.length;changed=deleted}audit('Bulk product action',x.action+' on '+ids.length+' products');save(db);return send(res,200,{ok:true,changed,deleted,products:db.products.map(safeProduct)})}
  if(req.method==='POST'&&p==='/api/admin/upload'){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const x=await body(req),name=String(x.name||'').replace(/[^a-zA-Z0-9._-]/g,'_'),data=String(x.data||''),m=data.match(/^data:(image\/(?:png|jpeg|webp));base64,(.+)$/);if(!name||!m||!['png','jpg','jpeg','webp'].includes(name.split('.').pop().toLowerCase()))return send(res,400,{error:'Only PNG, JPG and WEBP images are supported'});const buf=Buffer.from(m[2],'base64');if(buf.length>5*1024*1024)return send(res,413,{error:'Image must be 5MB or smaller'});const mediaDir=path.join(ROOT,'photos');fs.mkdirSync(mediaDir,{recursive:true});fs.writeFileSync(path.join(mediaDir,name),buf);return send(res,201,{ok:true,filename:name})}

  if(req.method==='POST'&&p==='/api/admin/coupons'){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const x=await body(req),code=String(x.code||'').trim().toUpperCase(),type=x.type==='fixed'?'fixed':'percent',value=Number(x.value||0);if(!/^[A-Z0-9_-]{3,30}$/.test(code)||value<=0)return send(res,400,{error:'Valid code and positive value required'});if(db.coupons.some(c=>c.code===code))return send(res,409,{error:'Coupon already exists'});const c={id:crypto.randomUUID(),code,type,value,minOrder:Math.max(0,Number(x.minOrder||0)),expiresAt:x.expiresAt||null,usageLimit:Math.max(0,Number(x.usageLimit||0)),active:true,uses:0};db.coupons.push(c);audit('Coupon created',code);save(db);return send(res,201,c)}
  if(req.method==='PATCH'&&p.startsWith('/api/admin/coupons/')){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const id=decodeURIComponent(p.slice('/api/admin/coupons/'.length)),c=db.coupons.find(v=>v.id===id);if(!c)return send(res,404,{error:'Coupon not found'});const x=await body(req);if(x.active!==undefined)c.active=Boolean(x.active);if(x.expiresAt!==undefined)c.expiresAt=x.expiresAt||null;if(x.type!==undefined)c.type=x.type==='fixed'?'fixed':'percent';if(x.value!==undefined&&Number(x.value)>0)c.value=Number(x.value);if(x.minOrder!==undefined)c.minOrder=Math.max(0,Number(x.minOrder)||0);if(x.usageLimit!==undefined)c.usageLimit=Math.max(0,Number(x.usageLimit)||0);audit('Coupon updated',c.code);save(db);return send(res,200,c)}
  if(req.method==='DELETE'&&p.startsWith('/api/admin/coupons/')){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const id=decodeURIComponent(p.slice('/api/admin/coupons/'.length)),i=db.coupons.findIndex(v=>v.id===id);if(i<0)return send(res,404,{error:'Coupon not found'});const c=db.coupons[i];db.coupons.splice(i,1);audit('Coupon deleted',c.code);save(db);return send(res,200,{ok:true})}
  if(req.method==='POST'&&p==='/api/returns'){const s=auth(req,'customer');const x=await body(req),id=String(x.orderId||'').trim(),o=db.orders.find(v=>v.orderId===id&&(!s||v.userId===s.userId));if(!o)return send(res,404,{error:'Order not found'});if(o.status!=='Delivered')return send(res,400,{error:'Only delivered orders can be returned'});const r={id:crypto.randomUUID(),orderId:id,reason:String(x.reason||'').slice(0,300),status:'Requested',createdAt:new Date().toISOString(),userId:o.userId||null};db.returns.push(r);audit('Return requested',id,'customer');save(db);return send(res,201,r)}
  if(req.method==='PATCH'&&p.startsWith('/api/admin/returns/')){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const id=decodeURIComponent(p.slice('/api/admin/returns/'.length)),r=db.returns.find(v=>v.id===id);if(!r)return send(res,404,{error:'Return not found'});const x=await body(req),allowed=['Requested','Approved','Pickup','Received','Refunded','Rejected'];if(!allowed.includes(x.status))return send(res,400,{error:'Invalid return status'});r.status=x.status;r.updatedAt=new Date().toISOString();audit('Return status',r.orderId+' → '+r.status);save(db);return send(res,200,r)}
  if(req.method==='GET'&&p==='/api/admin/audit'){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});return send(res,200,{audit:db.audit.slice(0,200)})}
  if(req.method==='DELETE'&&p.startsWith('/api/admin/newsletter/')){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const email=decodeURIComponent(p.slice('/api/admin/newsletter/'.length)).toLowerCase(),before=db.newsletter.length;db.newsletter=db.newsletter.filter(v=>v.email!==email);if(before===db.newsletter.length)return send(res,404,{error:'Subscriber not found'});save(db);return send(res,200,{ok:true})}
  if(req.method==='PATCH'&&p.startsWith('/api/admin/reviews/')){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const id=decodeURIComponent(p.slice('/api/admin/reviews/'.length)),x=await body(req),r=db.reviews.find(v=>v.id===id);if(!r)return send(res,404,{error:'Review not found'});if(x.approved!==undefined)r.approved=Boolean(x.approved);save(db);return send(res,200,r)}
  if(req.method==='GET'&&p==='/api/admin/backup'){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const safe={...db,sessions:{}};return send(res,200,safe)}
  if(req.method==='DELETE'&&p.startsWith('/api/admin/reviews/')){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const id=decodeURIComponent(p.slice('/api/admin/reviews/'.length)),before=db.reviews.length;db.reviews=db.reviews.filter(v=>v.id!==id);if(before===db.reviews.length)return send(res,404,{error:'Review not found'});save(db);return send(res,200,{ok:true})}
  if(req.method==='DELETE'&&p.startsWith('/api/admin/users/')){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const id=decodeURIComponent(p.slice('/api/admin/users/'.length)),i=db.users.findIndex(v=>v.id===id);if(i<0)return send(res,404,{error:'Customer not found'});db.users.splice(i,1);db.orders.forEach(o=>{if(o.userId===id)o.userId=null});save(db);return send(res,200,{ok:true})}
  return send(res,404,{error:'Not found'});
 }catch(e){console.error(e);return send(res,500,{error:'Server error'})}
}
const server=http.createServer(async(req,res)=>{const u=url.parse(req.url),p=u.pathname;if(p.startsWith('/api/'))return api(req,res,p);let file=path.normalize(path.join(ROOT,p==='/'?'index.html':p));if(!file.startsWith(ROOT)||!fs.existsSync(file)||fs.statSync(file).isDirectory())file=path.join(ROOT,'index.html');try{const ext=path.extname(file),buf=fs.readFileSync(file);res.writeHead(200,{'Content-Type':mime[ext]||'application/octet-stream'});res.end(buf)}catch{send(res,404,'Not found','text/plain')}});
server.listen(PORT,()=>console.log(`YOUR TYPE running at http://localhost:${PORT}`));
