const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),url=require('url');
const ROOT=__dirname, DATA=path.join(ROOT,'data.json'), PORT=process.env.PORT||3000;
const ADMIN_USER=process.env.ADMIN_USER||'admin';
const ADMIN_PASS=process.env.ADMIN_PASS||'';
const ADMIN_RESET_TOKEN=process.env.ADMIN_RESET_TOKEN||'';
const ADMIN_AUTH_FILE=path.join(ROOT,'admin-auth.json');
function strongPassword(s){return typeof s==='string'&&s.length>=12&&s.length<=128&&/[A-Z]/.test(s)&&/[a-z]/.test(s)&&/[0-9]/.test(s)&&/[^A-Za-z0-9]/.test(s)}
function hashPassword(s,salt){return crypto.scryptSync(String(s),salt,64).toString('hex')}
function loadAdminAuth(){try{return JSON.parse(fs.readFileSync(ADMIN_AUTH_FILE,'utf8'))}catch{return null}}
function saveAdminAuth(password){const salt=crypto.randomBytes(16).toString('hex');const auth={algorithm:'scrypt',salt,hash:hashPassword(password,salt),updatedAt:new Date().toISOString()};fs.writeFileSync(ADMIN_AUTH_FILE,JSON.stringify(auth,null,2),{mode:0o600});return auth}
let adminAuth=loadAdminAuth();
if(!adminAuth && ADMIN_PASS){if(!strongPassword(ADMIN_PASS)) console.warn('ADMIN_PASS is too weak. Set a 12+ character password with uppercase, lowercase, number and symbol.'); else adminAuth=saveAdminAuth(ADMIN_PASS)}
function verifyAdminPassword(password){if(!adminAuth)return false;const candidate=Buffer.from(hashPassword(password,adminAuth.salt),'hex'),stored=Buffer.from(adminAuth.hash,'hex');return candidate.length===stored.length&&crypto.timingSafeEqual(candidate,stored)}
const STATUSES=['New','Processing','Shipped','Delivered','Cancelled'];
function load(){try{return JSON.parse(fs.readFileSync(DATA,'utf8'))}catch{return {orders:[],newsletter:[],users:[],products:[],sessions:{}}}}
function save(db){fs.writeFileSync(DATA,JSON.stringify(db,null,2))}
const db=load(); db.orders ||= []; db.newsletter ||= []; db.users ||= []; db.products ||= []; db.sessions ||= {}; db.site ||= {hero:'YOUR TYPE',announcement:'New drops every week',sections:{home:true,collections:true,motion:true,featured:true,bestSellers:true,newCollection:true,trending:true,womenTops:true,highlights:true,editorial:true,newsletter:true},sectionProducts:{}}; db.site.sections ||= {home:true,collections:true,motion:true,featured:true,bestSellers:true,newCollection:true,trending:true,womenTops:true,highlights:true,editorial:true,newsletter:true}; db.site.sectionProducts ||= {}; db.site.sectionContent ||= {}; db.site.benefits ||= {}; db.site.newsletter ||= {};
db.products.forEach((p,i)=>{if(!p.id)p.id='p_'+crypto.createHash('sha1').update(p.name+'|'+p.image+'|'+i).digest('hex').slice(0,12);if(!p.sizes){const n=Math.max(0,Number(p.stock||0));p.sizes={S:n,M:n,L:n,XL:n,XXL:n}}});db.reviews ||= [];
function hash(s){return crypto.createHash('sha256').update(String(s)).digest('hex')}
function send(res,status,data,type='application/json'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'SAMEORIGIN','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Content-Security-Policy':"default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob:; img-src 'self' data: blob:; media-src 'self' blob:",'Access-Control-Allow-Origin':reqOrigin,'Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,PATCH,DELETE,OPTIONS'});res.end(type==='application/json'?JSON.stringify(data):data)}
let reqOrigin='';const rate=new Map();function limited(req,key,limit=60,windowMs=60000){const now=Date.now(),ip=req.socket.remoteAddress||'local',k=key+ip,arr=(rate.get(k)||[]).filter(t=>now-t<windowMs);arr.push(now);rate.set(k,arr);return arr.length>limit}
function body(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>2e6){req.destroy();return reject(new Error('Payload too large'))}});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}});req.on('error',reject)})}
function tokenFor(req){const h=req.headers.authorization||'';return h.startsWith('Bearer ')?h.slice(7):''}
function auth(req,role){const t=tokenFor(req),s=db.sessions[t];return s&&s.expires>Date.now()&&(!role||s.role===role)?s:null}
function newSession(role,userId){const token=crypto.randomBytes(32).toString('hex');db.sessions[token]={role,userId:userId||null,expires:Date.now()+8*60*60*1000};save(db);return token}
function orderId(){return 'YT-'+Date.now().toString(36).toUpperCase()+'-'+crypto.randomBytes(2).toString('hex').toUpperCase()}
function safeProduct(p){const z=p.sizes||{S:0,M:0,L:0,XL:0,XXL:0};const sizes={S:Math.max(0,Number(z.S||0)),M:Math.max(0,Number(z.M||0)),L:Math.max(0,Number(z.L||0)),XL:Math.max(0,Number(z.XL||0)),XXL:Math.max(0,Number(z.XXL||0))};return {id:p.id,name:String(p.name||''),price:String(p.price||''),image:String(p.image||''),images:Array.isArray(p.images)?p.images:[],badge:String(p.badge||''),oldPrice:String(p.oldPrice||''),description:String(p.description||''),category:String(p.category||'T-Shirts'),sku:String(p.sku||''),cost:Number(p.cost||0),sizes,colors:Array.isArray(p.colors)?p.colors:['Black','White','Charcoal'],active:p.active!==false,featured:Boolean(p.featured),sections:Array.isArray(p.sections)?p.sections:[],stock:Object.values(sizes).reduce((a,b)=>a+b,0)}}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp','.mp4':'video/mp4','.txt':'text/plain; charset=utf-8'};
async function api(req,res,p){
 try{reqOrigin=req.headers.origin&&req.headers.origin===('http://'+req.headers.host)?req.headers.origin:'';if(limited(req,p==='/api/admin/login'?'admin-login':p==='/api/admin/reset-password'?'admin-reset':p.startsWith('/api/admin')?'admin':p.startsWith('/api/auth')?'auth':'api',p==='/api/admin/login'?8:60,60000))return send(res,429,{error:'Too many requests. Please try again shortly.'});
  if(req.method==='OPTIONS')return send(res,204,'','text/plain');
  if(req.method==='POST'&&p==='/api/admin/login'){const x=await body(req);if(x.username!==ADMIN_USER||!verifyAdminPassword(x.password))return send(res,401,{error:'Invalid admin credentials'});return send(res,200,{token:newSession('admin')})}
  if(req.method==='POST'&&p==='/api/admin/change-password'){const s=auth(req,'admin');if(!s)return send(res,401,{error:'Unauthorized'});const x=await body(req);if(!verifyAdminPassword(x.currentPassword))return send(res,401,{error:'Current password is incorrect'});if(!strongPassword(x.newPassword))return send(res,400,{error:'New password must be 12–128 characters and include uppercase, lowercase, number and symbol'});adminAuth=saveAdminAuth(x.newPassword);db.sessions={};save(db);return send(res,200,{ok:true,message:'Password changed. Please sign in again.'})}
  if(req.method==='POST'&&p==='/api/admin/reset-password'){const x=await body(req);if(!ADMIN_RESET_TOKEN||x.resetToken!==ADMIN_RESET_TOKEN)return send(res,401,{error:'Invalid reset token'});if(!strongPassword(x.newPassword))return send(res,400,{error:'New password must be 12–128 characters and include uppercase, lowercase, number and symbol'});adminAuth=saveAdminAuth(x.newPassword);db.sessions={};save(db);return send(res,200,{ok:true,message:'Password reset successfully. Please sign in with the new password.'})}
  if(req.method==='POST'&&p==='/api/auth/signup'){const x=await body(req),name=String(x.name||'').trim(),email=String(x.email||'').trim().toLowerCase(),password=String(x.password||'');if(!name||!/^\S+@\S+\.\S+$/.test(email)||password.length<8)return send(res,400,{error:'Name, valid email and an 8+ character password are required'});if(db.users.some(u=>u.email===email))return send(res,409,{error:'Account already exists'});const u={id:crypto.randomUUID(),name,email,password:hash(password),createdAt:new Date().toISOString()};db.users.push(u);save(db);return send(res,201,{ok:true,token:newSession('customer',u.id),name,email})}
  if(req.method==='POST'&&p==='/api/auth/signin'){const x=await body(req),u=db.users.find(v=>v.email===String(x.email||'').trim().toLowerCase()&&v.password===hash(x.password||''));if(!u)return send(res,401,{error:'Invalid email or password'});return send(res,200,{ok:true,token:newSession('customer',u.id),name:u.name,email:u.email})}
  if(req.method==='GET'&&p==='/api/auth/me'){const s=auth(req,'customer');if(!s)return send(res,401,{error:'Unauthorized'});const u=db.users.find(v=>v.id===s.userId);if(!u)return send(res,404,{error:'Account not found'});return send(res,200,{id:u.id,name:u.name,email:u.email})}
  if(req.method==='GET'&&p==='/api/auth/orders'){const s=auth(req,'customer');if(!s)return send(res,401,{error:'Unauthorized'});return send(res,200,{orders:db.orders.filter(o=>o.userId===s.userId).map(o=>({orderId:o.orderId,status:o.status,date:o.date,total:o.total,items:o.items}))})}
  if(req.method==='POST'&&p==='/api/newsletter'){const x=await body(req),email=String(x.email||'').trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))return send(res,400,{error:'Invalid email'});if(!db.newsletter.some(v=>v.email===email))db.newsletter.push({email,createdAt:new Date().toISOString()});save(db);return send(res,201,{ok:true})}
  if(req.method==='GET'&&p==='/api/site-config'){db.site ||= {hero:'YOUR TYPE',announcement:'New drops every week',sections:{home:true,collections:true,motion:true,featured:true,bestSellers:true,newCollection:true,trending:true,womenTops:true,highlights:true,editorial:true,newsletter:true},sectionProducts:{}};return send(res,200,{site:db.site})}
  if(req.method==='PATCH'&&p==='/api/admin/site-config'){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const x=await body(req);db.site ||= {};if(x.hero!==undefined)db.site.hero=String(x.hero);if(x.announcement!==undefined)db.site.announcement=String(x.announcement);if(x.sections&&typeof x.sections==='object')db.site.sections=x.sections;if(x.sectionProducts&&typeof x.sectionProducts==='object')db.site.sectionProducts=x.sectionProducts;if(x.sectionContent&&typeof x.sectionContent==='object')db.site.sectionContent=x.sectionContent;if(x.benefits&&typeof x.benefits==='object')db.site.benefits=x.benefits;if(x.newsletter&&typeof x.newsletter==='object')db.site.newsletter=x.newsletter;['heroDescription','heroBtn1Text','heroBtn1Link','heroBtn2Text','heroBtn2Link','featured','social','phone','email'].forEach(k=>{if(x[k]!==undefined)db.site[k]=x[k]});save(db);return send(res,200,{ok:true,site:db.site})}
  if(req.method==='GET'&&p==='/api/products')return send(res,200,{products:db.products.map(safeProduct)});
  if(req.method==='GET'&&p.startsWith('/api/reviews/')){const name=decodeURIComponent(p.slice('/api/reviews/'.length));return send(res,200,{reviews:db.reviews.filter(r=>r.product===name).slice(-50).reverse()})}
  if(req.method==='POST'&&p==='/api/reviews'){const x=await body(req),name=String(x.product||'').trim(),title=String(x.title||'').trim(),text=String(x.text||'').trim(),rating=Math.max(1,Math.min(5,Number(x.rating||5)));if(!name||!title||!text||text.length>800)return send(res,400,{error:'Product, title and review text are required'});const sess=auth(req,'customer');if(!sess)return send(res,401,{error:'Please sign in to review'});const purchased=db.orders.some(o=>o.userId===sess.userId&&o.status!=='Cancelled'&&o.items?.some(it=>it.name===name));if(!purchased)return send(res,403,{error:'You can review a product after purchasing it.'});const u=db.users.find(v=>v.id===sess.userId);db.reviews.push({id:crypto.randomUUID(),product:name,rating,title,text,name:u?.name||'Customer',verified:true,createdAt:new Date().toISOString()});save(db);return send(res,201,{ok:true})}
  if(req.method==='POST'&&p==='/api/orders'){
    const x=await body(req);if(!x.name||!x.email||!x.phone||!x.address||!x.city||!/^\d{6}$/.test(String(x.pin))||!Array.isArray(x.items)||!x.items.length)return send(res,400,{error:'Complete shipping details and cart are required'});
    const requested=[];for(const item of x.items){const pr=db.products.find(v=>v.name===item.name&&v.image===item.image);if(!pr)return send(res,400,{error:'Product no longer available: '+item.name});const size=['S','M','L','XL','XXL'].includes(item.size)?item.size:'M';if(Number(pr.sizes?.[size]||0)<1)return send(res,409,{error:`${pr.name} size ${size} is out of stock`});requested.push({name:pr.name,image:pr.image,price:pr.price,size})}
    requested.forEach(item=>{const pr=db.products.find(v=>v.name===item.name&&v.image===item.image);pr.sizes[item.size]=Math.max(0,Number(pr.sizes[item.size]||0)-1)});
    const customer=auth(req,'customer'),id=orderId(),subtotal=requested.reduce((sum,item)=>sum+(Number(String(item.price).replace(/[^0-9.]/g,''))||0),0),shipping=subtotal>=999?0:99,total=subtotal+shipping,order={name:String(x.name).trim(),email:String(x.email).trim().toLowerCase(),phone:String(x.phone).trim(),address:String(x.address).trim(),city:String(x.city).trim(),pin:String(x.pin),items:requested,subtotal,shipping,total,payment:'cod',orderId:id,status:'New',date:new Date().toISOString(),userId:customer?.userId||null};
    db.orders.unshift(order);save(db);return send(res,201,{orderId:id,total:order.total})
  }
  if(req.method==='GET'&&p.startsWith('/api/orders/')){const id=decodeURIComponent(p.slice('/api/orders/'.length)),o=db.orders.find(v=>v.orderId===id);if(!o)return send(res,404,{error:'Order not found'});return send(res,200,{orderId:o.orderId,status:o.status,date:o.date,total:o.total,items:o.items})}
  if(req.method==='GET'&&p==='/api/admin/data'){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});return send(res,200,{orders:db.orders,newsletter:db.newsletter,products:db.products.map(safeProduct),users:db.users.map(u=>({id:u.id,name:u.name,email:u.email,createdAt:u.createdAt})),reviews:db.reviews})}
  if(req.method==='PATCH'&&p.startsWith('/api/admin/orders/')){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const id=decodeURIComponent(p.slice('/api/admin/orders/'.length)),x=await body(req),o=db.orders.find(v=>v.orderId===id);if(!o)return send(res,404,{error:'Order not found'});if(x.status&&!STATUSES.includes(x.status))return send(res,400,{error:'Invalid order status'});if(x.status)o.status=x.status;save(db);return send(res,200,o)}
  if(req.method==='DELETE'&&p.startsWith('/api/admin/orders/')){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const id=decodeURIComponent(p.slice('/api/admin/orders/'.length)),before=db.orders.length;db.orders=db.orders.filter(v=>v.orderId!==id);if(before===db.orders.length)return send(res,404,{error:'Order not found'});save(db);return send(res,200,{ok:true})}
  if(req.method==='POST'&&p==='/api/admin/products'){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const x=await body(req);if(!x.name||!x.price||!x.image)return send(res,400,{error:'Name, price and image filename are required'});const pr=safeProduct({...x,id:'p_'+crypto.randomBytes(6).toString('hex'),sizes:x.sizes||{S:0,M:0,L:0,XL:0,XXL:0}});db.products.push(pr);save(db);return send(res,201,pr)}
  if(req.method==='PATCH'&&p.startsWith('/api/admin/products/')){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const id=decodeURIComponent(p.slice('/api/admin/products/'.length)),x=await body(req),i=db.products.findIndex(v=>v.id===id);if(i<0)return send(res,404,{error:'Product not found'});const current=db.products[i];const updated=safeProduct({...current,...x,id:current.id,sizes:x.sizes||current.sizes});if(!updated.name||!updated.price||!updated.image)return send(res,400,{error:'Name, price and image filename are required'});db.products[i]=updated;save(db);return send(res,200,updated)}
  if(req.method==='DELETE'&&p.startsWith('/api/admin/products/')){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const id=decodeURIComponent(p.slice('/api/admin/products/'.length)),i=db.products.findIndex(v=>v.id===id);if(i<0)return send(res,404,{error:'Product not found'});db.products.splice(i,1);save(db);return send(res,200,{ok:true})}
  if(req.method==='DELETE'&&p.startsWith('/api/admin/reviews/')){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const id=decodeURIComponent(p.slice('/api/admin/reviews/'.length)),before=db.reviews.length;db.reviews=db.reviews.filter(v=>v.id!==id);if(before===db.reviews.length)return send(res,404,{error:'Review not found'});save(db);return send(res,200,{ok:true})}
  if(req.method==='DELETE'&&p.startsWith('/api/admin/users/')){if(!auth(req,'admin'))return send(res,401,{error:'Unauthorized'});const id=decodeURIComponent(p.slice('/api/admin/users/'.length)),i=db.users.findIndex(v=>v.id===id);if(i<0)return send(res,404,{error:'Customer not found'});db.users.splice(i,1);db.orders.forEach(o=>{if(o.userId===id)o.userId=null});save(db);return send(res,200,{ok:true})}
  return send(res,404,{error:'Not found'});
 }catch(e){console.error(e);return send(res,500,{error:'Server error'})}
}
const server=http.createServer(async(req,res)=>{const u=url.parse(req.url),p=u.pathname;if(p.startsWith('/api/'))return api(req,res,p);let file=path.normalize(path.join(ROOT,p==='/'?'index.html':p));if(!file.startsWith(ROOT)||!fs.existsSync(file)||fs.statSync(file).isDirectory())file=path.join(ROOT,'index.html');try{const ext=path.extname(file),buf=fs.readFileSync(file);res.writeHead(200,{'Content-Type':mime[ext]||'application/octet-stream'});res.end(buf)}catch{send(res,404,'Not found','text/plain')}});
server.listen(PORT,()=>console.log(`YOUR TYPE running at http://localhost:${PORT}`));
